//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.HumanBaxterCollaboration
{
    public class BaxterResultTrajectory : Message
    {
        public const string RosMessageName = "human_baxter_collaboration/BaxterResultTrajectory";

        //  message returning the result of the last trajectory issued
        public string arm;
        public bool success;

        public BaxterResultTrajectory()
        {
            this.arm = "";
            this.success = false;
        }

        public BaxterResultTrajectory(string arm, bool success)
        {
            this.arm = arm;
            this.success = success;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.arm));
            listOfSerializations.Add(BitConverter.GetBytes(this.success));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var armStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.arm = DeserializeString(data, offset, armStringBytesLength);
            offset += armStringBytesLength;
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "BaxterResultTrajectory: " +
            "\narm: " + arm.ToString() +
            "\nsuccess: " + success.ToString();
        }
    }
}
