//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.HumanBaxterCollaboration
{
    public class BaxterGripperOpen : Message
    {
        public const string RosMessageName = "human_baxter_collaboration/BaxterGripperOpen";

        //  msg to request a gripper to either open or close
        public bool open_gripper;

        public BaxterGripperOpen()
        {
            this.open_gripper = false;
        }

        public BaxterGripperOpen(bool open_gripper)
        {
            this.open_gripper = open_gripper;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.open_gripper));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.open_gripper = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "BaxterGripperOpen: " +
            "\nopen_gripper: " + open_gripper.ToString();
        }
    }
}
