//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.HumanBaxterCollaboration
{
    public class BaxterStopTrajectory : Message
    {
        public const string RosMessageName = "human_baxter_collaboration/BaxterStopTrajectory";

        //  message to stop current trajectory execution on Unity side
        //  empty, since its treated as an event
        public string arm;

        public BaxterStopTrajectory()
        {
            this.arm = "";
        }

        public BaxterStopTrajectory(string arm)
        {
            this.arm = arm;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.arm));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var armStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.arm = DeserializeString(data, offset, armStringBytesLength);
            offset += armStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "BaxterStopTrajectory: " +
            "\narm: " + arm.ToString();
        }
    }
}
